config/routes.rb
Rails.application.routes.draw do
  get 'employees/new'
  get 'employees/create'
  get 'contacts/new'
  get 'contacts/create'
  resources :daily_monitorings
  #get 'welcome/index'
  root to: 'welcome#index'
  
  get("/path1", { :controller => "medicines", :action => "create" })

  get("/path2", { :controller => "staffs", :action => "create" })

  
  resources :staffs, only: [:new, :create]
  

end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  address    :string
#  name       :string
#  phone      :string
#  position   :string
#  specialty  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Contact < ApplicationRecord
end

app/models/daily_monitoring.rb
# == Schema Information
#
# Table name: daily_monitorings
#
#  id          :integer          not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class DailyMonitoring < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/daily_monitorings_controller.rb
class DailyMonitoringsController < ApplicationController
  before_action :set_daily_monitoring, only: %i[ show edit update destroy ]

  # GET /daily_monitorings or /daily_monitorings.json
  def index
    @daily_monitorings = DailyMonitoring.all
  end

  # GET /daily_monitorings/1 or /daily_monitorings/1.json
  def show
  end

  # GET /daily_monitorings/new
  def new
    @daily_monitoring = DailyMonitoring.new
  end

  # GET /daily_monitorings/1/edit
  def edit
  end

  # POST /daily_monitorings or /daily_monitorings.json
  def create
    @daily_monitoring = DailyMonitoring.new(daily_monitoring_params)

    respond_to do |format|
      if @daily_monitoring.save
        format.html { redirect_to daily_monitoring_url(@daily_monitoring), notice: "Daily monitoring was successfully created." }
        format.json { render :show, status: :created, location: @daily_monitoring }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @daily_monitoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_monitorings/1 or /daily_monitorings/1.json
  def update
    respond_to do |format|
      if @daily_monitoring.update(daily_monitoring_params)
        format.html { redirect_to daily_monitoring_url(@daily_monitoring), notice: "Daily monitoring was successfully updated." }
        format.json { render :show, status: :ok, location: @daily_monitoring }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @daily_monitoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_monitorings/1 or /daily_monitorings/1.json
  def destroy
    @daily_monitoring.destroy

    respond_to do |format|
      format.html { redirect_to daily_monitorings_url, notice: "Daily monitoring was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_monitoring
      @daily_monitoring = DailyMonitoring.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def daily_monitoring_params
      params.require(:daily_monitoring).permit(:title, :description)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to root_path, notice: "Employee was successfully created."
    else
      render :new
    end
  end
  
  private
  
  def employee_params
    params.require(:employee).permit(:name, :address, :phone, :position, :specialty)
  end
  Add a route for the EmployeesController in config/routes.rb:
  
  ruby
  Copy code
  resources :employees, only: [:new, :create]
  Start the Rails server:
  
  Copy code
  rails server
  Visit http://localhost:3000/employees/new in your web browser to view the form and submit data.
  
  That's it! You should now have a working form with name, address, phone, position, and specialty fields that saves data to a database using Ruby on Rails.
  
  
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController

  def create
    render({ :template => "medicine_templates/create.html.erb"})
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to root_path, notice: "Employee was successfully created."
    else
      render :new
    end
  end
  
  private
  
  def employee_params
    params.require(:employee).permit(:name, :address, :phone, :position, :specialty)
  end
  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/daily_monitoring/_form.html.erb
<%= simple_form_for @daily_monitoring, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= error_span(@daily_monitoring[:title]) %>
  <%= f.input :description %>
  <%= error_span(@daily_monitoring[:description]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                daily_monitorings_path, :class => 'btn btn-default' %>
<% end %>

app/views/daily_monitoring/edit.html.erb
<%- model_class = DailyMonitoring -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/daily_monitoring/index.html.erb
<%- model_class = DailyMonitoring -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @daily_monitorings.each do |daily_monitoring| %>
      <tr>
        <td><%= link_to daily_monitoring.id, daily_monitoring_path(daily_monitoring) %></td>
        <td><%= daily_monitoring.title %></td>
        <td><%= daily_monitoring.description %></td>
        <td><%=l daily_monitoring.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      daily_monitoring_path(daily_monitoring), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_daily_monitoring_path(daily_monitoring), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      daily_monitoring_path(daily_monitoring),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_daily_monitoring_path,
            :class => 'btn btn-primary' %>

app/views/daily_monitoring/new.html.erb
<%- model_class = DailyMonitoring -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/daily_monitoring/show.html.erb
<%- model_class = DailyMonitoring -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @daily_monitoring.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @daily_monitoring.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              daily_monitorings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_daily_monitoring_path(@daily_monitoring), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              daily_monitoring_path(@daily_monitoring),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/daily_monitorings/_form.html.erb
<%= simple_form_for @daily_monitoring, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%#= error_span(@daily_monitoring[:title]) %>
  <%= f.input :description %>
  <%#= error_span(@daily_monitoring[:description]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                daily_monitorings_path, :class => 'btn btn-default' %>
<% end %>

app/views/daily_monitorings/edit.html.erb
<%- model_class = DailyMonitoring -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/daily_monitorings/index.html.erb
<%- model_class = DailyMonitoring -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @daily_monitorings.each do |daily_monitoring| %>
      <tr>
        <td><%= link_to daily_monitoring.id, daily_monitoring_path(daily_monitoring) %></td>
        <td><%= daily_monitoring.title %></td>
        <td><%= daily_monitoring.description %></td>
        <td><%=l daily_monitoring.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      daily_monitoring_path(daily_monitoring), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_daily_monitoring_path(daily_monitoring), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      daily_monitoring_path(daily_monitoring),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_daily_monitoring_path,
            :class => 'btn btn-primary' %>

app/views/daily_monitorings/new.html.erb
<%- model_class = DailyMonitoring -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/daily_monitorings/show.html.erb
<%- model_class = DailyMonitoring -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @daily_monitoring.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @daily_monitoring.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              daily_monitorings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_daily_monitoring_path(@daily_monitoring), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              daily_monitoring_path(@daily_monitoring),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/new.html.erb
<h1>Employees#new</h1>
<p>Find me in app/views/employees/new.html.erb</p>
<%= form_for @employee do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :specialty %>
    <%= f.text_field :specialty %>
  </div>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Final Project" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Transplant Patient</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Medicine", "/path1"  %></li>
            <li><%= link_to "Medical Staff", "/path2"  %></li>
            <li><%#= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Medicine", "/path1"  %></li>
              <li><%= link_to "Medical Staff", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; IBLASH 2023</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/medicine_templates/create.html.erb
Current Medicine Taking

app/views/staff_templates/create.html.erb
Attending Medical Staff

app/views/staff_templates/new.html.erb
<%= form_for @employee do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :specialty %>
    <%= f.text_field :specialty %>
  </div>
  <%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>